name: Docker vs WASM - Docker Runner

on: [push, pull_request]

jobs:
  test-docker:
    name: Run CI/CD in Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run CI Test in Docker
        run: |
          echo "🚀 Running test in Docker container"
          node test.js
